### PR TITLE
new DFU explaination video in readme

### PR DESCRIPTION
**Pull request by rananna**

### CODE REVIEW

**Comment by rananna** [comment]
Casainho,
Not sure what is going on, but when I made this pull request thinking that only one file has changed, it is showing me that you did not merge SDK_CONFIG, MAKEFILE,PINS.H,main.c, and NRF_BOOTLOADER from the last pull request!

This could explain why you were having so many problems with the board pin.
Could you please investigate?

**Comment by rananna** [comment]
Custom_board must also be updated for the pin to work.
Please just accept the entire PR as it is. It is working well for me.

**Comment by casainho** [comment]
Last time I merged manually, go and update your branch to see the your full code is on the main branch.

This new pull request also has conflicts. I think you have to update your branch before doing any more changes otherwise your PR can´t be merged due to the conflicts. Is better for me to not do other manual merge or there is the risk I will make errors on the code merge.

image

**Comment by rananna** [comment]
I not sure what you mean by " update your branch".
Everything is on branch "master" . I tried to reverse the pull request to pull from you to me, but the same conflicts are shown with an option to resolve manually. I have the same problem as you, if I did the changes manually I may mess up the code.
I don't understand enough about GitHub to fix this from my end.
Since the problem seems to be changes to files made in your repository that we don't need, perhaps the easiest thing to do is to delete all the files in your repository and accept the pull request from me?
Any other thoughts?

**Comment by casainho** [comment]
Seems I also can´t even merge manually.

I am also learning git as I need and this is the first time I am working so much with pull request so this issues are new to me.

I think the only option now is to consider the main branch on this repo as the original (https://github.com/OpenSource-EBike-firmware/TSDZ2_wireless-bootloader) and maybe you can delete your fork and fork again, and, add again your change to a fresh fork and make again the pull request. Sorry.

image

**Comment by rananna** [comment]
Oh boy, this is quite a mess.
I will try this.
Stand by.....

**Pull request closed without merging**
