### PR TITLE
Added versioning, cleaned up project directory

### PR DESCRIPTION
**Pull request by rananna**

### CODE REVIEW

**Comment by stsdc** [comment]
Check also what linter says:

```
 [firmware/main.c:241] -> [firmware/main.c:244]: (style) Variable 'err_code' is reassigned a value before the old one has been used.
[firmware/sdk/components/libraries/bootloader/dfu/nrf_dfu_ver_validation.c:4]: (error) #endif without #if
[firmware/main.c:158]: (style) The function 'app_error_fault_handler' is never used.
[firmware/main.c:152]: (style) The function 'app_error_handler' is never used.
[firmware/main.c:164]: (style) The function 'app_error_handler_bare' is never used.
```

**Comment by rananna** [comment]
app_error_handler_bare is used by ble.c
no issue with #endif found.
err_code is minor issue with app_error_check - fixed.
removed app_error_failt_handler & app_error_handler

**Comment by stsdc** [comment]
Ok, then. cppcheck needs to be tuned.

**Comment by stsdc** [comment]
Did You pushed these changes, because I can't see them here?

https://github.com/rananna/TSDZ2_wireless-bootloader/blob/1270a654c3dc0fe6391d12c845359bd81ecd2043/firmware/main.c#L164-L168

**Comment by rananna** [comment]
just pushed them now

**Comment by stsdc** [comment]
Are we patching `nrf_dfu_ver_validation.c` ?

**Comment by stsdc** [comment]
And there is still 
```
void app_error_handler_bare(uint32_t error_code)
{


    on_error();
}
```
https://github.com/rananna/TSDZ2_wireless-bootloader/blob/a845e6ddcefd12ed60da6445089254bb30a98b75/firmware/main.c#L165-L169

**Pull request merged**
