### PR TITLE
Release version

### PR DESCRIPTION
**Pull request by rananna**

### CODE REVIEW

**Comment by stsdc** [comment]
lets not put hex files into repo. there are tags and releases page on Github.

**Comment by rananna** [comment]
Ok.
 I made a release version in my fork for the PR, but it does not seem to get included in the PR.
@Casainho, could you please make a v1.0 release for the bootloader, and add the compiled hex file so that users can easily find it.
(Like I did in my fork)
I will update the readme to reference the compiled hex file and remove the 'release' folder

**Comment by rananna** [comment]
Done.

**Comment by casainho** [comment]
@rananna thanks for the release.

Maybe @stsdc can clarify if is possible to automate creating a release, since he did that when a git tag is created as like v1.0: https://github.com/OpenSource-EBike-firmware/TSDZ2_wireless/blob/master/.github/workflows/release.yml

I must say this the first time for me in all this of Continuous Integration...

**Comment by rananna** [comment]
The push was tagged as v1.0 in my fork, and the release was based on that.
Automation of releases would be a help

**Comment by stsdc** [comment]
@casainho You can merge this. I will prepare a new PR shortly with a release action. So we can finally test releasing.

**Pull request merged**
